//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kusovya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Должность.
    /// </summary>
    // *** Start programmer edit section *** (Должность CustomAttributes)

    // *** End programmer edit section *** (Должность CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДолжностьE", new string[] {
            "НомерДолжности as \'Номер должности\'",
            "Наименование as \'Наименование\'",
            "Сотрудник as \'Сотрудник\'",
            "Сотрудник.Имя as \'Имя\'"}, Hidden=new string[] {
            "Сотрудник.Имя"})]
    [MasterViewDefineAttribute("ДолжностьE", "Сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Имя")]
    [View("ДолжностьL", new string[] {
            "НомерДолжности as \'Номер должности\'",
            "Наименование as \'Наименование\'",
            "Сотрудник.Имя as \'Имя\'"})]
    public class Должность : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерДолжности;
        
        private string fНаименование;
        
        private IIS.Kusovya.Сотрудник fСотрудник;
        
        // *** Start programmer edit section *** (Должность CustomMembers)

        // *** End programmer edit section *** (Должность CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Должность.Наименование CustomAttributes)

        // *** End programmer edit section *** (Должность.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Должность.Наименование Get start)

                // *** End programmer edit section *** (Должность.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Должность.Наименование Get end)

                // *** End programmer edit section *** (Должность.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Должность.Наименование Set start)

                // *** End programmer edit section *** (Должность.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Должность.Наименование Set end)

                // *** End programmer edit section *** (Должность.Наименование Set end)
            }
        }
        
        /// <summary>
        /// НомерДолжности.
        /// </summary>
        // *** Start programmer edit section *** (Должность.НомерДолжности CustomAttributes)

        // *** End programmer edit section *** (Должность.НомерДолжности CustomAttributes)
        public virtual int НомерДолжности
        {
            get
            {
                // *** Start programmer edit section *** (Должность.НомерДолжности Get start)

                // *** End programmer edit section *** (Должность.НомерДолжности Get start)
                int result = this.fНомерДолжности;
                // *** Start programmer edit section *** (Должность.НомерДолжности Get end)

                // *** End programmer edit section *** (Должность.НомерДолжности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Должность.НомерДолжности Set start)

                // *** End programmer edit section *** (Должность.НомерДолжности Set start)
                this.fНомерДолжности = value;
                // *** Start programmer edit section *** (Должность.НомерДолжности Set end)

                // *** End programmer edit section *** (Должность.НомерДолжности Set end)
            }
        }
        
        /// <summary>
        /// Должность.
        /// </summary>
        // *** Start programmer edit section *** (Должность.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (Должность.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.Kusovya.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (Должность.Сотрудник Get start)

                // *** End programmer edit section *** (Должность.Сотрудник Get start)
                IIS.Kusovya.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (Должность.Сотрудник Get end)

                // *** End programmer edit section *** (Должность.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Должность.Сотрудник Set start)

                // *** End programmer edit section *** (Должность.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (Должность.Сотрудник Set end)

                // *** End programmer edit section *** (Должность.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДолжностьE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДолжностьE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДолжностьE", typeof(IIS.Kusovya.Должность));
                }
            }
            
            /// <summary>
            /// "ДолжностьL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДолжностьL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДолжностьL", typeof(IIS.Kusovya.Должность));
                }
            }
        }
    }
}
