//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kusovya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Рез опрос.
    /// </summary>
    // *** Start programmer edit section *** (РезОпрос CustomAttributes)

    // *** End programmer edit section *** (РезОпрос CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РезОпросE", new string[] {
            "НомерРез as \'Номер рез\'",
            "Оценка as \'Оценка\'",
            "Сотрудник as \'Сотрудник\'",
            "Сотрудник.Имя as \'Имя\'"}, Hidden=new string[] {
            "Сотрудник.Имя"})]
    [MasterViewDefineAttribute("РезОпросE", "Сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Имя")]
    [View("РезОпросL", new string[] {
            "НомерРез as \'Номер рез\'",
            "Оценка as \'Оценка\'",
            "Сотрудник.Имя as \'Имя\'"})]
    public class РезОпрос : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерРез;
        
        private int fОценка;
        
        private IIS.Kusovya.Сотрудник fСотрудник;
        
        // *** Start programmer edit section *** (РезОпрос CustomMembers)

        // *** End programmer edit section *** (РезОпрос CustomMembers)

        
        /// <summary>
        /// НомерРез.
        /// </summary>
        // *** Start programmer edit section *** (РезОпрос.НомерРез CustomAttributes)

        // *** End programmer edit section *** (РезОпрос.НомерРез CustomAttributes)
        public virtual int НомерРез
        {
            get
            {
                // *** Start programmer edit section *** (РезОпрос.НомерРез Get start)

                // *** End programmer edit section *** (РезОпрос.НомерРез Get start)
                int result = this.fНомерРез;
                // *** Start programmer edit section *** (РезОпрос.НомерРез Get end)

                // *** End programmer edit section *** (РезОпрос.НомерРез Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РезОпрос.НомерРез Set start)

                // *** End programmer edit section *** (РезОпрос.НомерРез Set start)
                this.fНомерРез = value;
                // *** Start programmer edit section *** (РезОпрос.НомерРез Set end)

                // *** End programmer edit section *** (РезОпрос.НомерРез Set end)
            }
        }
        
        /// <summary>
        /// Оценка.
        /// </summary>
        // *** Start programmer edit section *** (РезОпрос.Оценка CustomAttributes)

        // *** End programmer edit section *** (РезОпрос.Оценка CustomAttributes)
        public virtual int Оценка
        {
            get
            {
                // *** Start programmer edit section *** (РезОпрос.Оценка Get start)

                // *** End programmer edit section *** (РезОпрос.Оценка Get start)
                int result = this.fОценка;
                // *** Start programmer edit section *** (РезОпрос.Оценка Get end)

                // *** End programmer edit section *** (РезОпрос.Оценка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РезОпрос.Оценка Set start)

                // *** End programmer edit section *** (РезОпрос.Оценка Set start)
                this.fОценка = value;
                // *** Start programmer edit section *** (РезОпрос.Оценка Set end)

                // *** End programmer edit section *** (РезОпрос.Оценка Set end)
            }
        }
        
        /// <summary>
        /// Рез опрос.
        /// </summary>
        // *** Start programmer edit section *** (РезОпрос.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (РезОпрос.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.Kusovya.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (РезОпрос.Сотрудник Get start)

                // *** End programmer edit section *** (РезОпрос.Сотрудник Get start)
                IIS.Kusovya.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (РезОпрос.Сотрудник Get end)

                // *** End programmer edit section *** (РезОпрос.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РезОпрос.Сотрудник Set start)

                // *** End programmer edit section *** (РезОпрос.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (РезОпрос.Сотрудник Set end)

                // *** End programmer edit section *** (РезОпрос.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РезОпросE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РезОпросE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РезОпросE", typeof(IIS.Kusovya.РезОпрос));
                }
            }
            
            /// <summary>
            /// "РезОпросL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РезОпросL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РезОпросL", typeof(IIS.Kusovya.РезОпрос));
                }
            }
        }
    }
}
